import Link from 'next/link'
import './globals.css'
import LoginButton from './loginButton'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import LogoutButton from './logoutButton'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body>
        <div className='navbar'>
          <Link href="/" className='logo'>게시판</Link>
          <Link href="/list">List</Link>
          {
            session ? <LogoutButton/> : <LoginButton/>
          }
        </div>
        {children}
      </body>
    </html>
  )
}
